### ISSUE TITLE
[questions] is there a way to configure style or theme? + is there a way to split to left?

### ISSUE THREAD

**Issue by alexzanderr** [ezrafree/vscode-markdown-preview#1]
for example i have diff section:
![image](https://user-images.githubusercontent.com/54772464/132387090-bb79f565-0897-4879-b26d-728302139d79.png)
can i change the colors from vs code settings? instead of me going to the extension source code?

btw, i love this extensions, its great.

and i would really like a split to the `left`. is is possible?

thanks.

**Comment by ezrafree** [comment]
I'm closing this issue out as well, for the same reasons I mentioned in [the other issue](https://github.com/ezrafree/vscode-markdown-preview/issues/2#issuecomment-919308759).
