### ISSUE TITLE
[bug] markdown preview extension cancels the vs code auto-completion

### ISSUE THREAD

**Issue by alexzanderr** [ezrafree/vscode-markdown-preview#2]
i have a little self explanatory demo:
https://user-images.githubusercontent.com/54772464/132539685-9bfffecb-1910-44dc-a998-6522d48e7989.mp4
sorry about mistakes in the video. but you understood what i meant. and sorry, i couldnt embed the video with a little preview here. i dont know how to.

conclusion:
i dont get the usual autocomplete vs code popup window, only by pressing control+space.

**Comment by ezrafree** [comment]
I don't think this Markdown Preview extension could be causing that problem, there's [no .js](https://github.com/ezrafree/vscode-markdown-preview/blob/main/extension.js) in this extension and it only specifies [some CSS styles](https://github.com/ezrafree/vscode-markdown-preview/blob/main/style.css).

If you disable this `vscode-markdown-preview` extension does this bug still happen?

**Comment by alexzanderr** [comment]
> If you disable this vscode-markdown-preview extension does this bug still happen?
well, its not extension's fault. aparently vs code doesnt trigger automatically the auto-complete for markdown, only if I press `ctrl+space` to trigger that in order to see snippets and other words in the current file

**Comment by alexzanderr** [comment]
btw, i have to mention another 2 problems with this extension:
- when having live preview, the cursor is `flashing` every time i write a letter
- editor is moving up and down when there are more lines on the screen (here i have a recording)

https://user-images.githubusercontent.com/54772464/133236828-a105d248-093c-45ce-9665-43d5cacfb94d.mp4

**Comment by ezrafree** [comment]
Hi @alexzanderr,

Sorry but I still think you are misunderstanding what this extension does. My extension doesn't implement the Markdown Preview, that's a part of VS Code that comes with it already. My extension only adds a couple of styles to it, to improve usability/styling issues I found in VS Code's Markdown Preview. I recommend filing a bug with VS Code itself around any issues you're experiencing with their Markdown Preview pane.

**Comment by alexzanderr** [comment]
oh, my bad.
