### ISSUE TITLE
Suggestion: Checkbox color contrast options

### ISSUE THREAD

**Issue by EliseWei** [ezrafree/vscode-markdown-preview#4]
The grey checkbox works well for dark themes and white themes, but it's less visible in non-white light themes. Would it be possible to add a configuration option for either an alternate theme or vanilla HTML-style checkboxes?

White and dark:
![Screen Shot 2022-06-08 at 11 04 24 AM](https://user-images.githubusercontent.com/1482850/172497706-710b34b5-6e84-4718-9f02-d8e89c813290.png)
![Screen Shot 2022-06-08 at 11 05 00 AM](https://user-images.githubusercontent.com/1482850/172497703-17623693-79ce-4259-b1e5-119193d57c3d.png)

Light:
![Screen Shot 2022-06-08 at 11 06 55 AM](https://user-images.githubusercontent.com/1482850/172497742-0b8ab091-fa2f-4805-86f4-4fc7ad5334c7.png)
![Screen Shot 2022-06-08 at 11 05 16 AM](https://user-images.githubusercontent.com/1482850/172497744-479c221e-47d1-45b2-bef8-6b05078ccab5.png)

With vanilla-style HTML checkboxes:
![Screen Shot 2022-06-08 at 11 16 21 AM](https://user-images.githubusercontent.com/1482850/172498574-bb85402c-02b5-4b95-999b-c4a9a1638a5e.png)
![Screen Shot 2022-06-08 at 11 14 40 AM](https://user-images.githubusercontent.com/1482850/172498419-cc195f75-585f-4d57-9804-098ad489f12c.png)

Happy to help, if I can.

**Comment by ezrafree** [comment]
Hello! Apologies for the big delay here, but I've just updated the extension to use VS Code theme CSS colors, which from my testing fixes this issue for most themes, assuming they set a good color for the primary button color. If you see any issues, please be sure and comment back here with a link to the specific theme so I can test it directly. Thanks for the feedback!
